language: julia

os:
  - linux

julia:
  - 1.4

branches:
  only:
    - master
    - /^release-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    - mp/colortest

after_success:
  - if [ -f test/quietly.log ]; then cat test/quietly.log; fi
  - if [[ $TRAVIS_JULIA_VERSION = 1.1 ]] && [[ $TRAVIS_OS_NAME = linux ]]; then
      julia --project=coverage/ -e 'using Pkg; Pkg.instantiate();
          using Coverage; Codecov.submit(Codecov.process_folder())';
    fi

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Tests"

notifications:
  email: false
