language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0
  - nightly

notifications:
  email: false

after_success:
  - julia --project=coverage/ -e 'using Pkg; Pkg.instantiate()'
  - julia --project=coverage/ coverage/coverage.jl

jobs:
  include:
    - stage: "Documentation/HTML"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
    - stage: "Documentation/PDF"
      julia: 1.0
      os: linux
      services: docker
      script:
        - julia --project=docs/pdf/ -e 'using Pkg; Pkg.instantiate()'
        - julia --project=docs/pdf/ docs/pdf/make.jl
      after_success: skip
