language: julia

os:
  - linux
  - osx

julia:
  - 0.4
  - nightly

notifications:
  email: false

after_success:
  - julia -e 'cd(Pkg.dir("Lapidary")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
