site_name:           Lapidary.jl
repo_url:            https://github.com/MichaelHatherly/Lapidary.jl
site_description:    Julia package documentation generator.
site_author:         Michael Hatherly

theme:               readthedocs
extra_css:
  - Lapidary.css

markdown_extensions:
  - extra
  - tables
  - fenced_code
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js

docs_dir: 'docs/build'
pages:
  - 'About': index.md
  - 'Public': public.md
  - 'Internals': internals.md
