site_name:        Documenter.jl
repo_url:         https://github.com/MichaelHatherly/Documenter.jl
site_description: Julia package documentation generator.
site_author:      Michael Hatherly

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Home: index.md
- Manual:
  - Guide: man/guide.md
  - Examples: man/examples.md
  - Syntax: man/syntax.md
  - Doctests: man/doctests.md
  - Hosting Documentation: man/hosting.md
  - LaTeX Syntax: man/latex.md
  - Internals: man/internals.md
- Library:
  - Public: lib/public.md
  - Internals: lib/internals.md
